# config/moonshine.yml is loaded both by capistrano and moonshine.
#  The result is the values defined here can be used in `config/deploy.rb` directly
#  and in `app/manifest/application_manifest.rb` via `configuration`

# ruby to install at `cap deploy:setup` time. If you change this value, you
# need to run `cap ruby:upgrade`. Currently allowed values include: mri,
# src187, ree, ree187
:ruby: ree187

# Name of your application. Should be something with only alphanumerics, hypens
# and underscores.
:application: bostonrb

# Deploy user
:user: rails

# Timezone to set server's time to. Defaults to UTC
#:time_zone: UTC

# Directory where application is deployed to
:deploy_to: /srv/bostonrb

# Source control management to use. Defaults to git.
# If you change this value, you will need to run: cap vcs:install
#:scm: git
# Reposistory URI for checking out code at deploy time
:repository: git@github.com:bostonrb/bostonrb.git

# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
#:app_symlinks:
#  - system

# Use :shared_config to copy directories straight from your local project
# directory to the server: these are files that you don't have/want in scm.
:shared_config:
  - config/database.yml

# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config

# Passenger-specific options. Refer to the following templates for details
# about what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.conf.erb 
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/passenger.vhost.erb 
:passenger:
  :max_pool_size: 3

# MySQL-specific options. Refer to the following templates for details about
# what values are used:
# - vendor/plugins/moonshine/lib/moonshine/manifest/rails/templates/moonshine.cnf.erb 
:mysql:
  :innodb_buffer_pool_size: 128M
